version: '3.8'

# NETWORK
networks:
  nw:
    driver: bridge

services:
  # API-CONTACT 
  app:
    build: .
    ports:
      - "3003:3003"
    hostname: app
    networks:
      nw:
    extra_hosts:
      - "dockerhost:192.168.0.33"
    depends_on:
      - rabbitmq
    restart: on-failure

  # RABBITMQ : MESSAGING
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    networks:
      nw:
